name: doctor_repository
description: "the repo that handle doctor"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0-190.0.dev <4.0.0"
dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^4.16.1
  cupertino_icons: ^1.0.6
  email_otp: ^3.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.19.1
  firebase_core: ^2.27.1
  flutter_bloc: ^8.1.3
  uuid: ^4.4.2
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
