name: user_repository
description: "the repo that handle user"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.0.dev <4.0.0'
dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.19.1
  firebase_core: ^2.27.5
  firebase_storage: ^11.7.7
  flutter_bloc: ^8.1.5
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
